name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to the latest version compatible with Node.js 20

      # Step 2: Get Date
      - name: Get Date
        id: get-date
        run: |
          date=$(date -u +'%Y%m%d')
          echo "date=$date" >> $GITHUB_ENV  # Using environment variables instead of set-output
        shell: bash

      # Step 3: Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v4  # Updated to the latest version
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Step 4: Cache Buildozer local directory
      - name: Cache Buildozer local directory
        uses: actions/cache@v4  # Updated to the latest version
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      # Step 5: Build with Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      # Step 6: Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # Updated to the latest version
        with:
          name: package
          path: path/to/your/output.apk  # Ensure this path matches the actual output from Buildozer
