name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git operations

      # Step 2: Get Date
      - name: Get Date
        id: get-date
        run: |
          date=$(date -u +'%Y%m%d')
          echo "date=$date" >> $GITHUB_ENV  # Store the current date in an environment variable
        shell: bash

      # Step 3: Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Step 4: Cache Buildozer local directory
      - name: Cache Buildozer local directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      # Step 5: Attempt to remove Git config 'http.https://github.com/.extraheader'
      - name: Remove Git Extraheader
        run: |
          if git config --get http.https://github.com/.extraheader; then
            git config --unset-all http.https://github.com/.extraheader
          else
            echo "Git config 'http.https://github.com/.extraheader' not found."
          fi
        shell: bash

      # Step 6: Build with Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug  # Build the Android application in debug mode
          buildozer_version: master  # Use the latest version of Buildozer

      # Step 7: Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package  # Name of the uploaded artifact
          path: path/to/your/output.apk  # Replace with the actual path to the APK output from Buildozer
